*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Sep 15 21:39:48 2020] ***
compiled with version: 7.5.0 on 10 July 2020 03:47:40
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /home/bhrt_2/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5000 fd 3
uwsgi socket 1 bound to UNIX address malonoma_app.sock fd 4
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
Python main interpreter initialized at 0x557bad9cad10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20958)
spawned uWSGI worker 1 (pid: 20962, cores: 2)
spawned uWSGI worker 2 (pid: 20963, cores: 2)
spawned uWSGI worker 3 (pid: 20964, cores: 2)
spawned uWSGI worker 4 (pid: 20965, cores: 2)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
  File "./wsgi.py", line 1, in <module>
  File "./wsgi.py", line 1, in <module>
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from malonoma_app import malonoma_app as application
  File "./malonoma_app.py", line 2, in <module>
    from malonoma_app import malonoma_app as application
  File "./malonoma_app.py", line 2, in <module>
    from malonoma_app import malonoma_app as application
  File "./malonoma_app.py", line 2, in <module>
    from flask_restful import Resource, Api
ModuleNotFoundError: No module named 'flask_restful'
    from flask_restful import Resource, Api
unable to load app 0 (mountpoint='') (callable not found or import error)
ModuleNotFoundError: No module named 'flask_restful'
*** no app loaded. going in full dynamic mode ***
unable to load app 0 (mountpoint='') (callable not found or import error)
    from flask_restful import Resource, Api
*** no app loaded. going in full dynamic mode ***
    from malonoma_app import malonoma_app as application
ModuleNotFoundError: No module named 'flask_restful'
  File "./malonoma_app.py", line 2, in <module>
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
    from flask_restful import Resource, Api
ModuleNotFoundError: No module named 'flask_restful'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
--- no python application found, check your startup logs for errors ---
[pid: 20963|app: -1|req: -1/1] 127.0.0.1 () {34 vars in 439 bytes} [Tue Sep 15 21:39:57 2020] POST / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Sep 15 21:47:50 2020] ***
compiled with version: 7.5.0 on 10 July 2020 03:47:40
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /home/bhrt_2/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:5000).
bind(): Address already in use [core/socket.c line 769]
VACUUM: pidfile removed.
--- no python application found, check your startup logs for errors ---
[pid: 20963|app: -1|req: -1/2] 127.0.0.1 () {34 vars in 439 bytes} [Tue Sep 15 21:48:32 2020] POST / => generated 21 bytes in 85 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Sep 15 21:51:08 2020] ***
compiled with version: 7.5.0 on 14 July 2020 05:15:38
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5005 fd 3
uwsgi socket 1 bound to UNIX address malonoma_app.sock fd 4
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
Python main interpreter initialized at 0x557ac765cf10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21845)
spawned uWSGI worker 1 (pid: 21847, cores: 2)
spawned uWSGI worker 2 (pid: 21848, cores: 2)
spawned uWSGI worker 3 (pid: 21849, cores: 2)
spawned uWSGI worker 4 (pid: 21850, cores: 2)
2020-09-15 21:51:11.101725: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 21:51:11.102185: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 21:51:11.112619: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 21:51:11.112794: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 21:51:11.247326: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 21:51:11.247678: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 21:51:11.265175: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 21:51:11.265321: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 21:51:18.896652: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 21:51:18.896846: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 21:51:18.896968: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 21:51:18.897403: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 21:51:18.932434: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 21:51:18.933091: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557acada4290 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 21:51:18.933700: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 21:51:18.984153: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 21:51:18.984290: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 21:51:18.984392: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 21:51:18.984743: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 21:51:19.004560: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 21:51:19.008821: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557acada4190 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 21:51:19.008933: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 21:51:19.032698: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 21:51:19.033031: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 21:51:19.033527: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 21:51:19.035284: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 21:51:19.056160: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 21:51:19.056323: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 21:51:19.056428: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 21:51:19.056789: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 21:51:19.067762: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 21:51:19.068160: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557acada4190 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 21:51:19.068334: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 21:51:19.080639: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 21:51:19.081021: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557acada6550 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 21:51:19.081137: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Sep 15 22:36:04 2020] ***
compiled with version: 7.5.0 on 14 July 2020 05:15:38
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5005 fd 3
uwsgi socket 1 bound to UNIX address malonoma_app.sock fd 4
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
Python main interpreter initialized at 0x563958beff10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5035)
spawned uWSGI worker 1 (pid: 5038, cores: 2)
spawned uWSGI worker 2 (pid: 5039, cores: 2)
spawned uWSGI worker 3 (pid: 5040, cores: 2)
spawned uWSGI worker 4 (pid: 5041, cores: 2)
2020-09-15 22:36:06.497190: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 22:36:06.497295: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 22:36:06.512715: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 22:36:06.512855: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 22:36:06.566131: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 22:36:06.566214: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 22:36:06.592765: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 22:36:06.592936: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 22:36:12.300788: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 22:36:12.300937: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 22:36:12.312203: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 22:36:12.312627: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 22:36:12.313433: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 22:36:12.313520: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 22:36:12.313595: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 22:36:12.313936: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 22:36:12.328084: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 22:36:12.328432: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56395c338110 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 22:36:12.328517: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 22:36:12.339997: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 22:36:12.340383: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56395c337e60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 22:36:12.340481: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 22:36:12.401993: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 22:36:12.402097: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 22:36:12.402175: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 22:36:12.402526: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 22:36:12.420175: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 22:36:12.420552: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56395c337e40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 22:36:12.420652: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 22:36:12.448508: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 22:36:12.448600: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 22:36:12.448672: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 22:36:12.449032: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 22:36:12.464178: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 22:36:12.464557: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56395c337e60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 22:36:12.464655: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WSGI app 0 (mountpoint='') ready in 13 seconds on interpreter 0x563958beff10 pid: 5040 (default app)
WSGI app 0 (mountpoint='') ready in 13 seconds on interpreter 0x563958beff10 pid: 5041 (default app)
WSGI app 0 (mountpoint='') ready in 13 seconds on interpreter 0x563958beff10 pid: 5038 (default app)
WSGI app 0 (mountpoint='') ready in 13 seconds on interpreter 0x563958beff10 pid: 5039 (default app)
[pid: 5039|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 1735 bytes} [Tue Sep 15 22:37:05 2020] GET / => generated 51 bytes in 7 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 0)
[pid: 5039|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 1653 bytes} [Tue Sep 15 22:37:06 2020] GET /favicon.ico => generated 232 bytes in 0 msecs (HTTP/1.1 404) 3 headers in 119 bytes (1 switches on core 1)
[pid: 5039|app: 0|req: 3/3] 127.0.0.1 () {34 vars in 439 bytes} [Tue Sep 15 22:38:15 2020] POST / => generated 47 bytes in 3100 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
corrupted double-linked list
corrupted double-linked list
corrupted double-linked list
corrupted size vs. prev_size
worker 1 buried after 5 seconds
worker 2 buried after 5 seconds
worker 3 buried after 5 seconds
worker 4 buried after 5 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket malonoma_app.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Sep 15 23:44:27 2020] ***
compiled with version: 7.5.0 on 14 July 2020 05:15:38
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5005 fd 3
uwsgi socket 1 bound to UNIX address malonoma_app.sock fd 4
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
Python main interpreter initialized at 0x5573fb11af10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9837)
spawned uWSGI worker 1 (pid: 9841, cores: 2)
spawned uWSGI worker 2 (pid: 9842, cores: 2)
spawned uWSGI worker 3 (pid: 9843, cores: 2)
spawned uWSGI worker 4 (pid: 9844, cores: 2)
2020-09-15 23:44:48.380706: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:44:48.380861: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:44:48.383106: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:44:48.381111: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:44:48.381327: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:44:48.382156: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:44:48.403657: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:44:48.413689: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
SIGINT/SIGQUIT received...killing workers...
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Sep 15 23:45:33 2020] ***
compiled with version: 7.5.0 on 14 July 2020 05:15:38
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:5005).
bind(): Address already in use [core/socket.c line 769]
VACUUM: pidfile removed.
2020-09-15 23:45:42.483973: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:45:42.484470: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:45:42.483973: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:45:42.483973: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:45:42.485122: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:45:42.485209: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:45:42.484038: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:45:42.485605: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:45:42.484936: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:45:42.484986: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:45:42.485614: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:45:42.516736: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:45:42.517136: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:45:42.517447: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:45:42.517444: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:45:42.524155: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:45:42.592995: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:45:42.593246: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:45:42.593767: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:45:42.616613: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:45:42.622851: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5573fe864830 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:45:42.621519: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5573fe864820 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:45:42.623806: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5573fe864870 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:45:42.625386: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:45:42.624326: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:45:42.624792: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:45:42.627359: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5573fe864830 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:45:42.648339: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Tue Sep 15 23:46:23 2020 - worker 1 (pid: 9841) is taking too much time to die...NO MERCY !!!
Tue Sep 15 23:46:23 2020 - worker 2 (pid: 9842) is taking too much time to die...NO MERCY !!!
Tue Sep 15 23:46:23 2020 - worker 3 (pid: 9843) is taking too much time to die...NO MERCY !!!
Tue Sep 15 23:46:23 2020 - worker 4 (pid: 9844) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
unlink(): No such file or directory [core/uwsgi.c line 1617]
VACUUM: unix socket malonoma_app.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Sep 15 23:51:05 2020] ***
compiled with version: 7.5.0 on 14 July 2020 05:15:38
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5005 fd 3
uwsgi socket 1 bound to UNIX address malonoma_app.sock fd 4
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
Python main interpreter initialized at 0x55a9cd152f10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10283)
spawned uWSGI worker 1 (pid: 10286, cores: 2)
spawned uWSGI worker 2 (pid: 10287, cores: 2)
spawned uWSGI worker 3 (pid: 10288, cores: 2)
spawned uWSGI worker 4 (pid: 10289, cores: 2)
2020-09-15 23:51:26.550499: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:51:26.550975: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:51:26.550557: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:51:26.550705: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:51:26.551390: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:51:26.552302: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:51:26.579144: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:51:26.589466: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:52:42.633399: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:52:42.633582: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:52:42.633761: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:52:42.634468: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:52:42.671313: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:52:42.671539: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:52:42.671626: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:52:42.672011: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:52:42.728568: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:52:42.728870: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:52:42.728953: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:52:42.729021: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:52:42.729400: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:52:42.728574: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:52:42.728871: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:52:42.731955: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:52:42.732403: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:52:42.732765: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a9d089f760 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:52:42.732926: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:52:42.740782: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:52:42.742800: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:52:42.748968: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:52:42.758617: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a9d089f730 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:52:42.759373: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:52:42.759194: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a9d089f6d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:52:42.761798: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:52:42.759579: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a9d089f730 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:52:42.768809: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from malonoma_app import malonoma_app as application
  File "./malonoma_app.py", line 7, in <module>
    from recognize import pred
ModuleNotFoundError: No module named 'recognize'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
--- no python application found, check your startup logs for errors ---
[pid: 10286|app: -1|req: -1/1] 127.0.0.1 () {42 vars in 1747 bytes} [Tue Sep 15 23:52:59 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10286|app: -1|req: -1/2] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:52:59 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from malonoma_app import malonoma_app as application
  File "./malonoma_app.py", line 7, in <module>
    from recognize import pred
ModuleNotFoundError: No module named 'recognize'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from malonoma_app import malonoma_app as application
  File "./malonoma_app.py", line 7, in <module>
    from recognize import pred
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
ModuleNotFoundError: No module named 'recognize'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
    from malonoma_app import malonoma_app as application
  File "./malonoma_app.py", line 7, in <module>
    from recognize import pred
ModuleNotFoundError: No module named 'recognize'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
--- no python application found, check your startup logs for errors ---
[pid: 10287|app: -1|req: -1/3] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:53:59 2020] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10287|app: -1|req: -1/4] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:54:01 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 10287|app: -1|req: -1/5] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:54:24 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 10289|app: -1|req: -1/6] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:54:40 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10289|app: -1|req: -1/7] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:54:41 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 10287|app: -1|req: -1/8] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:54:42 2020] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 10287|app: -1|req: -1/9] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:55:03 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 10289|app: -1|req: -1/10] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:55:04 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 10289|app: -1|req: -1/11] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:55:06 2020] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
SIGINT/SIGQUIT received...killing workers...
corrupted size vs. prev_size
corrupted size vs. prev_size
corrupted size vs. prev_size
corrupted size vs. prev_size
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Sep 15 23:55:44 2020] ***
compiled with version: 7.5.0 on 14 July 2020 05:15:38
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:5005).
bind(): Address already in use [core/socket.c line 769]
VACUUM: pidfile removed.
worker 1 buried after 3 seconds
worker 2 buried after 3 seconds
worker 3 buried after 3 seconds
worker 4 buried after 3 seconds
goodbye to uWSGI.
unlink(): No such file or directory [core/uwsgi.c line 1617]
VACUUM: unix socket malonoma_app.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Sep 15 23:57:45 2020] ***
compiled with version: 7.5.0 on 14 July 2020 05:15:38
os: Linux-4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020
nodename: Jarvis
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages
writing pidfile to process.pid
detected binary path: /media/bhrt_2/Entertainment/Skin_Cancer_detection_AGBI/flask_api/Malonoma_stages/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30413
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5005 fd 3
uwsgi socket 1 bound to UNIX address malonoma_app.sock fd 4
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
Python main interpreter initialized at 0x560d35d0df10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11442)
spawned uWSGI worker 1 (pid: 11443, cores: 2)
spawned uWSGI worker 2 (pid: 11444, cores: 2)
spawned uWSGI worker 3 (pid: 11445, cores: 2)
spawned uWSGI worker 4 (pid: 11446, cores: 2)
2020-09-15 23:57:48.757515: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:57:48.757814: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:57:48.762205: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:57:48.762533: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:57:48.772135: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:57:48.772259: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:57:48.814838: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-15 23:57:48.814967: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-15 23:57:55.195222: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:57:55.195401: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:57:55.195538: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:57:55.198357: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:57:55.215062: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:57:55.215263: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:57:55.215381: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:57:55.218758: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:57:55.235758: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:57:55.240000: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560d39458cf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:57:55.240251: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:57:55.252009: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:57:55.252508: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560d39456c70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:57:55.252651: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:57:55.342446: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:57:55.342586: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:57:55.342697: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:57:55.343255: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:57:55.362302: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:57:55.363871: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560d39456c70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:57:55.364266: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 23:57:55.580510: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-09-15 23:57:55.581044: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-15 23:57:55.581779: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jarvis): /proc/driver/nvidia/version does not exist
2020-09-15 23:57:55.583363: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-15 23:57:55.633335: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-09-15 23:57:55.633821: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560d39458dc0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 23:57:55.633920: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WSGI app 0 (mountpoint='') ready in 16 seconds on interpreter 0x560d35d0df10 pid: 11444 (default app)
[pid: 11444|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 1766 bytes} [Tue Sep 15 23:58:01 2020] GET / => generated 51 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 0)
WSGI app 0 (mountpoint='') ready in 16 seconds on interpreter 0x560d35d0df10 pid: 11446 (default app)
WSGI app 0 (mountpoint='') ready in 17 seconds on interpreter 0x560d35d0df10 pid: 11445 (default app)
WSGI app 0 (mountpoint='') ready in 17 seconds on interpreter 0x560d35d0df10 pid: 11443 (default app)
[pid: 11445|app: 0|req: 1/2] 127.0.0.1 () {34 vars in 442 bytes} [Tue Sep 15 23:58:18 2020] POST / => generated 103 bytes in 2 msecs (HTTP/1.1 400) 3 headers in 113 bytes (1 switches on core 1)
./test/bharat.png
[pid: 11443|app: 0|req: 1/3] 127.0.0.1 () {34 vars in 442 bytes} [Tue Sep 15 23:59:08 2020] POST / => generated 47 bytes in 1735 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
corrupted double-linked list
corrupted size vs. prev_size
corrupted double-linked list
corrupted size vs. prev_size
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket malonoma_app.sock removed.
